openapi: 3.0.2
info:
  title: Steria server API
  description: ''
  version: 0.0.2
servers:
- url: https://steria.herokuapp.com
tags:
- name: House info v1.0
  description: ''
- name: House info v1.1
  description: ''

paths:
  /v1/house:
    get:
      tags:
        - House info v1.0
      summary: "Получить информацию о здании по точному адресу"
      description: "Возвращает набор параметров о здании или ошибку. Если адрес не уникальный и было найдено более одного адреса - будет возвращена ошибка."
      parameters:
        - name: address
          in: query
          description: "Манежный пер 15-17"
          required: true
          schema:
            type: string

      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                title: Sample
                type: object
                properties:
                  r_adress:
                    type: string
                  r_name:
                    type: string
                  r_architect:
                    type: string
                  r_style:
                    type: string
                  r_years_string:
                    type: string


        500:
          description: Successful response
          content:
            application/json:
              schema:
                title: Sample
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      Error:
                        type: string
                        title: "Сообщение об ошибке"




  /v1.1/houses/getByAddress:
    get:
      tags:
        - House info v1.1
      summary: "Получить информацию о здании по точному адресу"
      description: "Получить массив с краткой информацией о зданиях, адрес которых примерно совпадает с переданным в параметре. Необходимо указать количество найденных совпадений. Если совпадения не найдены то возвращается пустой массив с `count=0`."
      parameters:
      - $ref: '#/components/parameters/address'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                title: Sample
                type: object
                properties:
                  houses:
                    type: array
                    items:
                      $ref: '#/components/schemas/HouseItem'
                  count:
                    title: "Количество записей в разделе"
                    type: integer


  /v1.1/houses/{house_id}:
    get:
      tags:
        - House info v1.1
      summary: "Получить информацию о здании по его id"
      description: "Возвращает набор параметров о здании или ошибку"
      parameters:
       - $ref: '#/components/parameters/house_id'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                title: HouseData
                type: object
                properties:
                  full_address:
                    description: "Полный адрес здания!! Указать название столбцов в базе"
                    example: test
                    type: string
                  title:
                    description: "Название здания"
                    example: test
                    type: string
                  architect:
                    description: "Имя или имена архитекторов"
                    example: test
                    type: string
                  style:
                    description: "Название архитектурного стиля здания"
                    example: test
                    type: string
                  buildYears:
                    description: "Год строительства здания"
                    example: test
                    type: string
                  URL:
                    description: "Ссылка на оффициальный сайт"
                    example: test
                    type: string
        404:
          description: Not found response
          content:
            application/json:
              schema:
                title: Error
                type: object
                properties:
                  message:
                    description: "Сообщение клиенту"
                    type: object
                    properties:
                      error:
                        description: "Ошибка"
                        type: string


components:
  parameters:
    house_id:
      name: house_id
      in: path
      required: true
      example: 22
      schema:
        type: integer
    address:
      name: address
      in: query
      required: true
      example: "Манежный пер 15-17!!!"
      description: "**Фрагмент адреса**. Пример: `Манежный пер 15-17`"
      schema:
        type: string
  schemas:
    HouseItem:
      title: House
      type: object
      properties:
        address:
          $ref: '#/components/parameters/address'
        house_id:
          $ref: '#/components/parameters/house_id'
        title:
          type: string
        id:
          type: integer





